Repository ddwu-sw-system-dev/oisan-api, pull requests merged in 2022-06, with the labels that each got.

#5 Add: Auction Bidding JPA 추가
  src/main/java/com/example/oisan/SchedulerConfig.java
  src/main/java/com/example/oisan/controller/AuctionCommand.java
  src/main/java/com/example/oisan/controller/AuctionController.java
  src/main/java/com/example/oisan/controller/AuctionFilterCommand.java
  src/main/java/com/example/oisan/controller/BiddingCommand.java
  src/main/java/com/example/oisan/controller/BiddingController.java
  src/main/java/com/example/oisan/domain/Auction.java
  src/main/java/com/example/oisan/domain/Bidding.java
  src/main/java/com/example/oisan/domain/Furniture.java
  src/main/java/com/example/oisan/repository/AuctionRepository.java
  src/main/java/com/example/oisan/repository/BiddingRepository.java
  src/main/java/com/example/oisan/service/AuctionService.java
  src/main/java/com/example/oisan/service/BiddingService.java
Labels: implement

#7 Feature/#2 customer jpa
  src/main/java/com/example/oisan/command/CustomerUpdateCommand.java
  src/main/java/com/example/oisan/command/LoginCommand.java
  src/main/java/com/example/oisan/controller/AuctionController.java
  src/main/java/com/example/oisan/controller/BiddingController.java
  src/main/java/com/example/oisan/controller/ChatRoomController.java
  src/main/java/com/example/oisan/controller/CustomerController.java
  src/main/java/com/example/oisan/controller/SearchController.java
  src/main/java/com/example/oisan/dao/OiPayUsageDao.java
  src/main/java/com/example/oisan/dao/jpa/JpaOiPayUsageDao.java
  src/main/java/com/example/oisan/domain/Chat.java
  src/main/java/com/example/oisan/domain/ChatRoom.java
  src/main/java/com/example/oisan/domain/Customer.java
  src/main/java/com/example/oisan/domain/OiPayUsage.java
  src/main/java/com/example/oisan/exception/AuthenticationException.java
  src/main/java/com/example/oisan/exception/CustomerNotFoundException.java
  src/main/java/com/example/oisan/exception/NotMatchPwException.java
  src/main/java/com/example/oisan/repository/ChatRepository.java
  src/main/java/com/example/oisan/repository/ChatRoomRepository.java
  src/main/java/com/example/oisan/repository/CustomerRepository.java
  src/main/java/com/example/oisan/service/AuctionService.java
  src/main/java/com/example/oisan/service/ChatRoomService.java
  src/main/java/com/example/oisan/service/CustomerService.java
Labels: implement, fix

#14 fix: Auction DTO에 Customer 포함하도록 수정
  src/main/java/com/example/oisan/controller/AuctionController.java
  src/main/java/com/example/oisan/domain/Auction.java
  src/main/java/com/example/oisan/repository/AuctionRepository.java
  src/main/java/com/example/oisan/service/AuctionService.java
Labels: implement, fix

#16 Feature/#15 chat list api
  src/main/java/com/example/oisan/controller/ChatRoomController.java
  src/main/java/com/example/oisan/domain/Chat.java
  src/main/java/com/example/oisan/repository/ChatRepository.java
  src/main/java/com/example/oisan/service/ChatRoomService.java
Labels: fix, add

#19 add: customer exception, sequence
  src/main/java/com/example/oisan/controller/CustomerController.java
  src/main/java/com/example/oisan/controller/LoginCommand.java
  src/main/java/com/example/oisan/domain/Customer.java
  src/main/java/com/example/oisan/service/CustomerService.java
Labels: add

#21 fix: auction size filtering
  src/main/java/com/example/oisan/controller/AuctionController.java
  src/main/java/com/example/oisan/controller/AuctionFilterCommand.java
Labels: fix

#25 add: price in post, datetime in chat
  src/main/java/com/example/oisan/controller/ChatRoomController.java
  src/main/java/com/example/oisan/controller/PostCommand.java
  src/main/java/com/example/oisan/domain/Post.java
  src/main/java/com/example/oisan/service/PostService.java
Labels: add

#32 add: find chatroom by customer ids
  src/main/java/com/example/oisan/controller/ChatRoomController.java
Labels: add

#34 add: join chatroom with customer
  src/main/java/com/example/oisan/domain/ChatRoom.java
Labels: add

#36 자잘한 수정 및 Bidding Command 삭제
  src/main/java/com/example/oisan/controller/AuctionController.java
  src/main/java/com/example/oisan/controller/BiddingCommand.java
  src/main/java/com/example/oisan/controller/BiddingController.java
  src/main/java/com/example/oisan/service/BiddingService.java
Labels: fix

#39 fix: customerId를 파라미터로 받아오도록 수정
  src/main/java/com/example/oisan/controller/AuctionController.java
  src/main/java/com/example/oisan/controller/BiddingController.java
  src/main/java/com/example/oisan/service/AuctionService.java
Labels: fix

#41 add: post like list in post detail
  pom.xml
  src/main/java/com/example/oisan/controller/PostController.java
  src/main/java/com/example/oisan/domain/Chat.java
  src/main/java/com/example/oisan/domain/Post.java
  src/main/java/com/example/oisan/domain/PostLike.java
  src/main/java/com/example/oisan/repository/PostLikeRepository.java
  src/main/java/com/example/oisan/repository/PostRepository.java
  src/main/java/com/example/oisan/service/PostService.java
Labels: add

#43 fix: modifying 관련 반환 값 변경
  src/main/java/com/example/oisan/controller/AuctionController.java
  src/main/java/com/example/oisan/domain/Auction.java
  src/main/java/com/example/oisan/domain/Bidding.java
  src/main/java/com/example/oisan/repository/AuctionRepository.java
  src/main/java/com/example/oisan/service/AuctionService.java
Labels: fix

#45 add: customer like post list
  src/main/java/com/example/oisan/domain/Customer.java
Labels: add

#48 Add: post tag, 거래 완료 상태로 업데이트 구현
  src/main/java/com/example/oisan/controller/PostController.java
  src/main/java/com/example/oisan/domain/Moodtag.java
  src/main/java/com/example/oisan/domain/TagPost.java
  src/main/java/com/example/oisan/repository/AuctionRepository.java
  src/main/java/com/example/oisan/repository/BiddingRepository.java
  src/main/java/com/example/oisan/repository/MoodtagRepository.java
  src/main/java/com/example/oisan/repository/PostRepository.java
  src/main/java/com/example/oisan/repository/TagPostRepository.java
  src/main/java/com/example/oisan/service/PostService.java
Labels: implement, add

#50 Feature/#49 bidding insert
  src/main/java/com/example/oisan/controller/BiddingController.java
  src/main/java/com/example/oisan/domain/Bidding.java
  src/main/java/com/example/oisan/repository/BiddingRepository.java
  src/main/java/com/example/oisan/service/BiddingService.java
  src/main/java/com/example/oisan/service/OiPayUsageService.java
Labels: fix

#51 fix: auction 생성자 순서 변경
  src/main/java/com/example/oisan/service/AuctionService.java
Labels: fix

#53 implement: upload image s3
  pom.xml
  src/main/java/com/example/oisan/controller/PostCommand.java
  src/main/java/com/example/oisan/controller/PostController.java
  src/main/java/com/example/oisan/service/PostService.java
  src/main/java/com/example/oisan/service/S3FileUploadService.java
  src/main/resources/application.properties
Labels: implement

#55 fix: get bidding list by auctionId
  src/main/java/com/example/oisan/controller/BiddingController.java
  src/main/java/com/example/oisan/repository/BiddingRepository.java
  src/main/java/com/example/oisan/service/BiddingService.java
Labels: fix

#57 refactor: api를 하나로 합침
  src/main/java/com/example/oisan/controller/PostController.java
Labels: fix

#58 fix: tag list 반환 값 변경
  src/main/java/com/example/oisan/controller/PostController.java
Labels: fix

#56 add: upload image in auction
  src/main/java/com/example/oisan/controller/AuctionCommand.java
  src/main/java/com/example/oisan/controller/AuctionController.java
  src/main/java/com/example/oisan/controller/PostController.java
  src/main/java/com/example/oisan/service/AuctionService.java
  src/main/java/com/example/oisan/service/PostService.java
  src/main/java/com/example/oisan/service/S3FileService.java
Labels: implement, fix, add

#59 Feature/cressorigin
  src/main/java/com/example/oisan/controller/PostController.java
  src/main/java/com/example/oisan/controller/SearchController.java
Labels: fix

#60 fix: method name
  src/main/java/com/example/oisan/controller/ChatRoomController.java
Labels: fix

#62 test bidding
  src/main/java/com/example/oisan/service/AuctionService.java
Labels: test

#66 fix: image- null to old url & add: auctionId in auction command
  src/main/java/com/example/oisan/controller/AuctionCommand.java
  src/main/java/com/example/oisan/service/AuctionService.java
  src/main/java/com/example/oisan/service/PostService.java
Labels: fix, add

#64 Add: winning auction 조회 기능
  src/main/java/com/example/oisan/controller/AuctionController.java
  src/main/java/com/example/oisan/controller/BiddingController.java
  src/main/java/com/example/oisan/controller/PostController.java
  src/main/java/com/example/oisan/repository/BiddingRepository.java
  src/main/java/com/example/oisan/service/AuctionService.java
Labels: add

#70 add: like post list
  src/main/java/com/example/oisan/controller/CustomerController.java
  src/main/java/com/example/oisan/domain/PostLike.java
  src/main/java/com/example/oisan/repository/CustomerRepository.java
  src/main/java/com/example/oisan/service/AuctionService.java
  src/main/java/com/example/oisan/service/CustomerService.java
Labels: add
